### ISSUE TITLE
Commutative property

### ISSUE THREAD

**Issue by mydatamodels** [sdpython/mlprodict#283]
Hello,
I was testing mlprodict, but playing with the first tutorial I ran into a blocking situation for me.
```
from typing import Any
import numpy as np
import mlprodict.npy.numpy_onnx_impl as npnx
from mlprodict.npy import onnxnumpy_default, NDArray


# The numpy function
def log_1(x):
    return np.log(1 + x)


# The ONNX function
@onnxnumpy_default
def onnx_log_1(x: NDArray[Any, np.float32]) -> NDArray[Any, np.float32]:
    return npnx.log(np.float32(1) + x)


x = np.random.rand(2, 3).astype(np.float32)

print('numpy')
print(log_1(x))

print('onnx')
print(onnx_log_1(x))
```
It's the tutorial http://www.xavierdupre.fr/app/mlprodict/helpsphinx/tutorial/numpy_api_onnx.html#principle with inverted addends.
Running it I get the following error:
```
Traceback (most recent call last):
  File "/home/mvm/code/onnx/tutorial.py", line 14, in <module>
    def onnx_log_1(x: NDArray[Any, np.float32]) -> NDArray[Any, np.float32]:
  File "/home/mvm/venvs/onnx/lib/python3.9/site-packages/mlprodict/npy/onnx_numpy_wrapper.py", line 110, in onnxnumpy_default
    return onnxnumpy()(fct)
  File "/home/mvm/venvs/onnx/lib/python3.9/site-packages/mlprodict/npy/onnx_numpy_wrapper.py", line 88, in decorator_fct
    compiled = OnnxNumpyCompiler(
  File "/home/mvm/venvs/onnx/lib/python3.9/site-packages/mlprodict/npy/onnx_numpy_compiler.py", line 140, in __init__
    self.onnx_ = self._to_onnx(
  File "/home/mvm/venvs/onnx/lib/python3.9/site-packages/mlprodict/npy/onnx_numpy_compiler.py", line 333, in _to_onnx
    onx_var = self.fct_(*names_var, **kwargs)
  File "/home/mvm/code/onnx/tutorial.py", line 15, in onnx_log_1
    return npnx.log(np.float32(1) + x)
TypeError: unsupported operand type(s) for +: 'float' and 'OnnxVar'
```
Am i missing something or is there a problem?

Best regards.

**Comment by xadupre** [comment]
There is a conflict between operator __add__ from np.float32 and OnnxVar. You need to write `x + np.float32(1)` to select `OnnxVar.__add__`.

**Comment by mydatamodels** [comment]
Is there any way to cast a np.float32 to OnnxVar?

Thanks

**Comment by sdpython** [comment]
One way to do it is ``npnx.log(npnx.identity(np.array([1], dtype=np.float32)) + x)``. I'll make something more convenient.

**Comment by sdpython** [comment]
In the next release (tomorrow), it will be possible to write  ``npnx.log(npnx.cst(1.) + x)``. Does that work for you?

**Comment by mydatamodels** [comment]
I can get around the problem easier that way, thanks!
