### ISSUE TITLE
plot_grid_search.py: TypeError: shape must contains integers not 'None'.

### ISSUE THREAD

**Issue by adrinjalali** [sdpython/mlprodict#36]
The example fails to run:

```python
$ python _doc/examples/plot_grid_search.py 
Traceback (most recent call last):
  File "_doc/examples/plot_grid_search.py", line 51, in <module>
    model, initial_types=[('X', FloatTensorType((None, X.shape[1])))])
  File "/path/to//site-packages/skl2onnx/convert.py", line 123, in convert_sklearn
    custom_shape_calculators, custom_parsers)
  File "/path/to//site-packages/skl2onnx/_parse.py", line 353, in parse_sklearn_model
    inputs.append(scope.declare_local_variable(var_name, initial_type))
  File "/path/to//site-packages/skl2onnx/common/_topology.py", line 307, in declare_local_variable
    variable = Variable(raw_name, onnx_name, self.name, type)
  File "/path/to//site-packages/skl2onnx/common/_topology.py", line 73, in __init__
    "'{}'.".format(dim))
TypeError: shape must contains integers not 'None'.
```

**Comment by adrinjalali** [comment]
Interesting, it actually works on skl2onnx's master, but not with the one on pypi.

**Comment by sdpython** [comment]
True, this modification was introduced to leave a dimension unknown. ONNX can be very precise about dimension but the number of observations in batch predictions is always unknown. That's why the first dimension of a shape is usually None. This convention was not always followed but it is now.

**Comment by sdpython** [comment]
I'll close the issue. It will disappear with the next release of skl2onnx.
